<package format="3">
  <name>asimov</name>
  <version>1.0.0</version>
  <description>
    <p>URDF Description package for asimov</p>
    <p>This package contains configuration data, 3D models and launch files
for asimov robot</p>
  </description>
  <author>TODO</author>
  <maintainer email="TODO@email.com">TODO</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>robot_state_publisher</depend>
  <depend>joint_state_publisher_gui</depend>
  <depend>rviz2</depend>
  <depend>ros2_control</depend>
  <depend>ros2_controllers</depend>
  <depend>ign_ros2_control</depend>
  <depend>ros_gz_sim</depend>
  <depend>ros_gz_bridge</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
